[package]
name = "qiita_poise"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] } 

poise = "0.6" 
serenity = "0.12" 

dotenvy = "0.15" 

thiserror = "1.0" 

env_logger = "0.10" 
log = "0.4"